pipelines-test-2/Pages/Albums/AlbumsFormViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using data.test.com.Models;
using data.test.com.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace data.test.com.Pages.Albums
{
	public class AlbumsFormViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke(AlbumModel album)
		{
			ViewData["Artists"] = ArtistService.GetAll().Select(a => new SelectListItem
			{
				Value = a.ArtistID.ToString(),
				Text = a.Title,
				Selected = album?.ArtistID == a.ArtistID
			});
			return View("Default", album);
		}
	}
}

pipelines-test-2/Pages/Albums/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using data.test.com.Models;
using data.test.com.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace data.test.com.Pages.Albums
{
	[Authorize(Roles = "Administrator")]
	public class EditModel : PageModel
	{
		public AlbumModel Album { get; set; }

		public void OnGet(int albumID)
		{
			Album = AlbumService.GetById(albumID);
		}

		public IActionResult OnPost(AlbumModel album)
		{
			if (!ModelState.IsValid)
			{
				Album = album;
				return Page();
			}

			AlbumService.Update(album);
			return RedirectToPage("/Albums/Index");
		}
	}
}

pipelines-test-2/Pages/Albums/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using data.test.com.Models;
using data.test.com.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace data.test.com.Pages.Albums
{
	[Authorize(Roles = "Administrator, ChartWriter")]
	public class IndexModel : PageModel
	{
		[BindProperty(SupportsGet = true)]
		public int? ArtistID { get; set; }

		public IEnumerable<SelectListItem> Artists { get; set; }
		public IEnumerable<AlbumModel> List { get; set; }

		public void OnGet()
		{
			List = AlbumService.GetAll(ArtistID);
			Artists = ArtistService.GetAll().Select(a => new SelectListItem
			{
				Value = a.ArtistID.ToString(),
				Text = a.Title,
				Selected = ArtistID == a.ArtistID
			});
		}
	}
}

pipelines-test-2/Pages/Albums/New.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using data.test.com.Models;
using data.test.com.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace data.test.com.Pages.Albums
{
	[Authorize(Roles = "Administrator")]
	public class NewModel : PageModel
	{
		public void OnGet()
		{

		}

		public IActionResult OnPost(AlbumModel album)
		{
			if (!ModelState.IsValid)
			{
				return Page();
			}

			AlbumService.New(album);
			return RedirectToPage("/Albums/Index");
		}
	}
}

pipelines-test-2/Pages/Parts/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using data.test.com.Models;
using data.test.com.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace data.test.com.Pages.Parts
{
	public class EditModel : PageModel
	{
		public PartModel Part { get; set; }
		public IEnumerable<SelectListItem> Categories { get; set; }

		public void OnGet(int partID)
		{
			Part = PartService.GetById(partID);
			Categories = PartCategoryService.GetAll().Select(a => new SelectListItem
			{
				Value = a.CategoryID.ToString(),
				Text = a.Title
			});
		}

		public IActionResult OnPost(PartModel part)
		{
			if (!ModelState.IsValid)
			{
				Categories = PartCategoryService.GetAll().Select(a => new SelectListItem
				{
					Value = a.CategoryID.ToString(),
					Text = a.Title,
					Selected = part.CategoryID == a.CategoryID
				});
				return Page();
			}

			PartService.Update(part);
			return RedirectToPage("/Parts/Index");
		}
	}
}

pipelines-test-2/Pages/Parts/New.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using data.test.com.Models;
using data.test.com.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace data.test.com.Pages.Parts
{
	public class NewModel : PageModel
	{
		public PartModel Part{ get; set; }
		public IEnumerable<SelectListItem> Categories { get; set; }

		public void OnGet()
		{
			Part = new PartModel();
			Categories = PartCategoryService.GetAll().Select(a => new SelectListItem
			{
				Value = a.CategoryID.ToString(),
				Text = a.Title
			});
		}

		public IActionResult OnPost(PartModel part)
		{
			if (!ModelState.IsValid)
			{
				Categories = PartCategoryService.GetAll().Select(a => new SelectListItem
				{
					Value = a.CategoryID.ToString(),
					Text = a.Title,
					Selected = part.CategoryID == a.CategoryID
				});
				return Page();
			}

			PartService.New(part);
			return RedirectToPage("/Parts/Index");
		}
	}
}

pipelines-test-2/Pages/Albums/Edit.cshtml
@page "{albumID:int}"
@model EditModel
@{
	ViewData["Title"] = "Edit Album " + Model.Album.Title;
}

@await Component.InvokeAsync("AlbumsForm", new { album = Model.Album })

pipelines-test-2/Pages/Albums/Index.cshtml
@page
@model data.test.com.Pages.Albums.IndexModel
@{
    ViewData["Title"] = "Albums";
}

	<div class="text-center">
		<h1 class="display-4">Albums</h1>
		<form asp-action="Index" method="get">
			<div class="form-actions no-color">
				<p>
					Find by Artist: @Html.DropDownList("artistID", Model.Artists, "All Artists")
					<input type="submit" value="Search" class="btn btn-default" /> |
					<a asp-page="/albums/new">New</a>
				</p>
			</div>
		</form>
		<table class="table">
			<thead>
				<tr>
					<th>
						ID
					</th>
					<th>
						Title
					</th>
					<th>
						Artist
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model.List)
				{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.AlbumID)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Title)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Artist)
						</td>
						<td>
							<a asp-page="/albums/edit" asp-route-albumID="@item.AlbumID">Edit</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>

pipelines-test-2/Pages/Albums/New.cshtml
@page
@model NewModel
@{
	ViewData["Title"] = "New Album";
}

@await Component.InvokeAsync("AlbumsForm", new { album = new AlbumModel { AlbumID = 0 } })